lemonade_soapbox/views/frontend.py
from flask import render_template, request, url_for
from whoosh.query import Term as whoosh_term

from lemonade_soapbox.models import Article, Review
from lemonade_soapbox.helpers import Blueprint, read_changelog

bp = Blueprint('frontend', __name__, static_folder='assets')


@bp.app_errorhandler(404)
def error404(e):
    return render_template('frontend/404.html'), 404


@bp.route('/')
def index():
    articles = (
        Article.published().order_by(Article.date_published.desc()).limit(5).all()
    )
    reviews = Review.published().order_by(Review.date_published.desc()).limit(5).all()
    return render_template(
        'frontend/index.html', articles=articles, page_title='', reviews=reviews
    )


@bp.route('/search/')
def search():
    """Searching, obviously."""
    q = request.args.get('q')
    page = request.args.get('page', 1, int)
    per_page = request.args.get('per_page', 20, int)
    page_title = 'Search'
    articles = None
    if q:
        search_params = {
            'pagenum': page,
            'pagelen': per_page,
            'filter': whoosh_term('status', 'published'),  # Only return published posts
            'sort_order': request.args.get('sort', 'asc'),
        }

        if sort_by := request.args.get('sortby'):
            search_params['sort_field'] = sort_by

        articles = Article.search(q, **search_params)
        if articles:
            page_title = (
                f"{articles.total} article{'s' if articles.total > 1 else ''} found"
            )
        else:
            page_title = "No articles found"
    return render_template(
        'blog/views/article_list.html',
        cover=url_for(
            '.static',
            filename='images/layout/header_bg/regine-tholen-pAs8r_VZEWc-unsplash.jpg',
        ),
        page_title=page_title,
        articles=articles,
    )


@bp.route('/about/')
def about_me():
    return render_template('frontend/about.html', page_title='About Me')


@bp.route('/changelog/')
def changelog():
    """Display the contents of the changelog."""
    contents, toc_dict = read_changelog("tachyondecay.net")
    return render_template(
        "frontend/changelog.html",
        page_title="Changelog",
        changelog_contents=contents,
        toc_dict=toc_dict,
    )


@bp.route('/editing/')
def editing():
    return render_template(
        'frontend/editing.html',
        page_title='Freelance Editing Services',
    )


@bp.route('/podcasts/')
def podcasts():
    return render_template('frontend/podcasts.html', page_title='My Podcasts')

lemonade_soapbox/templates/frontend/layouts/main.html
<!doctype html>
<html lang="en" class="lg:text-lg xl:text-xl bg-slate-50 text-slate-700 scroll-pt-10">
    <head>
        <title>{% block page_title %}{{ page_title }} | Kara Babcock{% endblock %}</title>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <meta name="twitter:site" content="@tachyondecay">
        <meta name="twitter:creator" content="@tachyondecay">
        {% block meta_tags %}
        <meta name="description" content="Personal blog of Kara Babcock, book reviewer, copyeditor, and podcaster." />
        <meta property="og:url" content="{{ request.base_url }}" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Kara Babcock" />
        <meta property="og:description" content="Personal blog of Kara Babcock, book reviewer, copyeditor, and podcaster." />
        <meta property="og:image" content="{{ url_for('.static', filename='images/headshots/opengraph-banner-2025-03.jpg', _external=True) }}">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
        <meta name="twitter:card" content="summary_large_image">
        {% endblock %}

        <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,700;1,400&family=Oswald:wght@300;400;700&display=swap" rel="stylesheet">
        {% block styles %}
        <link rel="stylesheet" href="{{ url_for('.static', filename='css/tachyondecay.css') }}"/>
        {% endblock %}

        {% block scripts %}
        
        {% endblock %}

        {% block feeds %}
        <link rel="alternate"  href="{{ url_for('blog.show_feed', format='rss') }}" title="Articles RSS feed"/>
        <link rel="alternate" href="{{ url_for('blog.show_feed', format='atom') }}" title="Articles Atom feed"/>
        {% endblock %}

        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('.static', filename='images/icons/apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('.static', filename='images/icons/favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('.static', filename='images/icons/favicon-16x16.png') }}">
        <link rel="manifest" href="{{ url_for('.static', filename='site.webmanifest') }}">
    </head>
    <body class="{% block body_classes %}{% endblock %}">
    <div class="flex sticky top-0 z-10 justify-center items-center px-8 h-10 bg-fuchsia-900 shadow-md md:justify-between shadow-marble-600/50">
        <div class="hidden mr-4 md:block md:overflow-hidden md:flex-1 md:text-fuchsia-50 md:whitespace-nowrap md:text-ellipsis">{{ self.page_title() }}</div>
        <div>
            <a class="mr-8 text-fuchsia-50 before:content-['⬆']" href="#top" title="Jump to top of page">Start</a>
            <a class="text-fuchsia-50 after:content-['⬇']" href="#colophon" title="Jump to footer">End</a>
        </div>
    </div>

    {% block body_main %}
        <header class="border-t-8 border-fuchsia-900 lg:flex lg:absolute lg:top-0 lg:right-0 lg:left-0 lg:z-30 lg:px-11 lg:pt-6 lg:pb-4 lg:text-lg lg:bg-neutral-50" id="top">
            {% block navigation %}
            <nav class="flex relative z-20 flex-col pb-3 md:flex-row md:items-end md:pt-6 lg:p-0 lg:bg-transparent -mt-[2.1rem] bg-marble-100 md:bg-neutral-50 lg:grow-[2] lg:shrink lg:basis-auto" aria-label="Primary Site Navigation">
                <div class="flex border-b shadow-md md:flex-1 md:ml-6 md:rounded-md md:border-b-0 lg:mr-3 lg:ml-6 border-slate-400 shadow-slate-400/25 md:basis-1/5 lg:grow-[3]">
                    <form action="{{ url_for('frontend.search') }}" class="contents">
                        <input type="search" class="p-3 border-0 opacity-50 transition-all duration-300 md:rounded-l-lg focus:ring-inset focus:opacity-100 peer grow-[3] text-sky-900 focus:ring-sky-700" name="q" placeholder="Search blog posts…" value="{{ request.args.get('q', '') }}">
                        <button type="submit" value="Go" title="Search" class="text-center transition-all md:rounded-r-lg duration-600 basis-20 bg-slate-100 text-slate-400 peer-focus:bg-sky-700/20 peer-focus:text-sky-900 md:grow-0 md:shrink md:basis-10 hover:bg-sky-700/20">
                            <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                            </svg>
                        </button>
                    </form>
                </div>

                <ul role="list" class="flex flex-wrap justify-around items-center my-3 md:flex-auto md:justify-end md:my-0 md:mr-3">
                    <li class="m-3 md:my-0">
                        <a class="uppercase border-b-2 border-fuchsia-900 lg:text-sm hover:border-sky-900 focus:border-sky-900" href="/about/" title="Learn more about me!">About Me</a>
                    </li>
                    <li class="m-3 md:my-0">
                        <a class="uppercase border-b-2 border-fuchsia-900 lg:text-sm hover:border-sky-900 focus:border-sky-900" href="/blog/" title="Read my personal blog">Blog</a>
                    </li>
                    <li class="m-3 md:my-0">
                        <a class="uppercase border-b-2 border-fuchsia-900 lg:text-sm hover:border-sky-900 focus:border-sky-900" href="https://kara.reviews/" title="Go to my book reviews website">Book Reviews</a>
                    </li>
                    <li class="m-3 md:my-0">
                        <a class="uppercase border-b-2 border-fuchsia-900 lg:text-sm hover:border-sky-900 focus:border-sky-900" href="/podcasts/" title="Learn more about my two podcasts">Podcasts</a>
                    </li>
                    <li class="m-3 md:my-0">
                        <a class="uppercase border-b-2 border-fuchsia-900 lg:text-sm hover:border-sky-900 focus:border-sky-900" href="/editing/" title="I offer freelance editing services">Editing</a>
                    </li>
                </ul>

                <a href="#colophon" class="inline-block flex-1 mx-auto text-xs after:content-['↴'] border-b-2 uppercase border-fuchsia-900 md:mx-3  hover:border-sky-900  focus:border-sky-900">Jump to End</a>
            </nav>
            {% endblock navigation %}

            <div class="p-2 my-6 lg:order-first lg:p-0 lg:m-0 lg:flex-0 lg:grow-0 lg:shrink-0 lg:basis-auto">
                <a href="/" class="flex justify-center items-center">
                    <img class="min-w-0 h-28 rounded-full sm:h-32 lg:max-h-12" src="{{ url_for('.static', filename='images/headshots/kara-babcock-2024-04-06 12.24.39.jpg') }}" alt="Headshot of me with long hair, pink lip stick, light makeup">
                    <img class="ml-2 min-w-0 h-24 sm:h-28 lg:max-h-10" src="{{ url_for('.static', filename='images/tachyondecay.net-logo.png') }}" alt="Kara Babcock">
                </a>
            </div>

            {% block header_end %}{% endblock header_end %}
        </header>
    {% endblock body_main %}

    {% block body_footer %}
        <footer class="p-3 mt-24 sm:border-t md:mt-36 lg:p-0 lg:bg-transparent bg-slate-200 border-b-[6px] border-b-fuchsia-900 sm:border-t-slate-200" id="colophon">
            <h2 class="sr-only">Colophon</h2>

            <div class="mt-10 mb-3 w-full text-xs font-normal text-center lg:pb-3 xl:px-12 xl:pb-0 xl:mt-3 xl:text-2xs">
                Copyright ©2025 <a href="mailto:kara@tachyondecay.net" class="underline">Kara Babcock</a>. Blog posts licensed under a <a class="underline" href="http://creativecommons.org/licenses/by/4.0/" rel="license">Creative Commons Attribution 4.0 Licence</a><img class="inline mx-px h-3" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="Creative Commons logo"><img class="inline mx-px h-3" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="Creative Commmons Attribution logo">
            </div>
        </footer>
    {% endblock body_footer %}

        <script data-goatcounter="https://tachyondecay.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
        {% block body_scripts %}
        <script src="https://cdn.jsdelivr.net/npm/mustache@4.2.0/mustache.min.js"></script>
        <script src="https://cdn.plyr.io/3.6.12/plyr.js"></script>
        <script src="{{ url_for('.static', filename='js/tachyondecay.js') }}"></script>
        {% endblock %}
    </body>
</html>