lemonade_soapbox/views/blog.py
import calendar
from gettext import ngettext
from pathlib import Path

import arrow
from flask import (
    abort,
    current_app,
    redirect,
    render_template,
    request,
    Response,
    url_for,
)
from flask_login import current_user, login_required

from lemonade_soapbox import db
from lemonade_soapbox.helpers import Blueprint
from lemonade_soapbox.models import Article, Post, Tag

bp = Blueprint('blog', __name__)


@bp.errorhandler(404)
def error404(e):
    return render_template('blog/errors/404.html'), 404


@bp.route('/')
def index():
    page = request.args.get('page', 1, int)
    articles = (
        Article.published()
        .order_by(Article.date_published.desc())
        .paginate(page=page, per_page=10)
    )
    return render_template(
        'blog/views/index.html',
        articles=articles,
        description="Read my thoughts going back 21 years.",
        page_title="Kara’s Blog",
    )


@bp.route('/drafts/<handle>/')
@login_required
def show_draft(handle):
    article = Article.query.filter_by(handle=handle, status='draft').first_or_404()
    return render_template('blog/views/single_article.html', article=article)


@bp.route('/trash/<handle>/')
@login_required
def show_deleted(handle):
    article = Article.query.filter_by(handle=handle, status='deleted').first_or_404()
    return render_template('blog/views/single_article.html', article=article)


@bp.route('/feed/')
def default_feed():
    return redirect(
        url_for('.show_feed', format=current_app.config['DEFAULT_FEED_FORMAT'])
    )


@bp.route('/feed/posts.<format>')
def show_feed(format):
    articles = (
        Article.published().order_by(Article.date_published.desc()).limit(10).all()
    )
    return Response(
        render_template(
            'blog/articles/' + format + '.xml',
            articles=articles,
            url=url_for('blog.show_feed', _external=True, format=format),
        ),
        mimetype='application/' + format + '+xml',
    )


@bp.route('/tags/')
def all_tags():
    tags = [t for t in Tag.frequency(post_types=['article']) if t[1] > 0]
    sort_by = request.args.get('sort', 'frequency')
    page_title = ngettext('%(num)d Tag', 'All %(num)d Tags', len(tags)) % {
        'num': len(tags)
    }
    return render_template(
        'blog/views/tags.html', page_title=page_title, tags=tags, sort_by=sort_by
    )


@bp.route('/tags/<handle>/')
@bp.route('/tags/<handle>/posts.<format>')
def show_tag(handle, format=None):
    page = request.args.get('page', 1, int)
    tag = Tag.query.filter_by(handle=handle).first_or_404()
    articles = tag.posts.filter(
        Post.post_type == "article",
        Post.status == 'published',
        Post.date_published <= arrow.utcnow(),
    ).order_by(Post.date_published.desc())

    if format:
        return Response(
            render_template(
                'blog/articles/' + format + '.xml',
                title=f'Kara.Reviews: {tag.label.title()} Books',
                articles=articles.all(),
                url=url_for(
                    'blog.show_tag',
                    _external=True,
                    handle=handle,
                    format=format,
                ),
            ),
            mimetype='application/' + format + '+xml',
        )

    articles = articles.paginate(page=page, per_page=20)

    cover = None
    if Path(
        current_app.static_folder, 'images/layout/header_bg', f"{handle}.jpg"
    ).exists():
        cover = url_for(
            '.static', filename=f"images/layout/header_bg/{handle}.jpg", _external=True
        )

    return render_template(
        'blog/views/article_list.html',
        handle=handle,
        read_more_length=75,
        articles=articles,
        page_title=f"Articles Tagged with “{tag.label}”",
        cover=cover,
    )


@bp.route('/<int:year>/')
def year_archive(year):
    start, end = arrow.get(year, 1, 1).span('year')
    articles = (
        Article.published()
        .filter(Article.date_published.between(start, end))
        .order_by(Article.date_published.desc())
        .all()
    )
    if not articles:
        abort(404)

    # Check if there are posts for previous and next years
    prev_link = (
        Article.published()
        .filter(db.func.extract('YEAR', Article.date_published) == (year - 1))
        .count()
        > 0
    )
    next_link = (
        Article.published()
        .filter(db.func.extract('YEAR', Article.date_published) == (year + 1))
        .count()
        > 0
    )

    year_summaries = {
        "2004": "First year of high school, first real job, first year online.",
        "2005": "In which I discover Doctor Who, move high schools, and get political.",
        "2006": "Learning how to drive, playing with Linux, and more politics.",
        "2007": "Pop culture, environmental awareness, and high school graduation.",
        "2008": "Joining Twitter and Goodreads, visiting an online friend, discovering Mass Effect.",
        "2009": "Lots of thoughts on technology, more politics.",
        "2010": "A summer spent researching mathematics, my first smartphone.",
        "2011": "In which I was very into voting for the Hugo Awards.",
        "2012": "Learning how to knit, graduating university, and moving to England.",
        "2013": "Living and teaching in England and a lot of pop culture.",
        "2014": "Trip to Amsterdam, moving back to Canada, new phone who dis?",
        "2015": "In which I start blogging seriously about education.",
        "2016": "Critical reflections on education, algorithms, and some lighter fare in knitting.",
        "2017": "On being asexual and aromantic, buying a house, and meeting my ride or die",
        "2018": "Starting a podcast with my bestie, visiting her in Montréal.",
        "2019": "More reflections on being an educator in Ontario.",
        "2020": "Coming out as trans, launching Kara.Reviews.",
        "2021": "Transition during a pandemic and reflections on friendship and pop culture.",
        "2022": "The current year. I hope it’s a good one!",
    }

    return render_template(
        'blog/views/year_archive.html',
        articles=articles,
        page_title=f"{len(articles)} Articles from {year}",
        prev_link=prev_link,
        next_link=next_link,
        month_name=calendar.month_name,
        year=year,
        year_summaries=year_summaries,
    )


@bp.route('/<int:year>/<month>/')
def month_archive(year, month):
    if int(month) not in range(1, 13):
        abort(404)
    start, end = arrow.get(year, int(month), 1).span('month')
    articles = (
        Article.published()
        .filter(Article.date_published.between(start, end))
        .order_by(Article.date_published.desc())
        .all()
    )
    if not articles:
        abort(404)

    # Check if there are posts for previous and next months
    prev_article = (
        Article.published()
        .filter(Article.date_published < articles[-1].date_published)
        .order_by(Article.date_published.desc())
        .first()
    )
    prev_link = (
        (
            url_for(
                ".month_archive",
                year=prev_article.date_published.year,
                month=f"{prev_article.date_published.month:02}",
            ),
            prev_article.date_published.format("MMMM YYYY"),
        )
        if prev_article
        else None
    )
    next_article = (
        Article.published()
        .filter(Article.date_published > articles[0].date_published)
        .order_by(Article.date_published.asc())
        .first()
    )
    next_link = (
        (
            url_for(
                ".month_archive",
                year=next_article.date_published.year,
                month=f"{next_article.date_published.month:02}",
            ),
            next_article.date_published.format("MMMM YYYY"),
        )
        if next_article
        else None
    )

    return render_template(
        'blog/views/article_list.html',
        articles=articles,
        description=f"{len(articles)} articles",
        prev_link=prev_link,
        next_link=next_link,
        page_title=f"Articles from {calendar.month_name[int(month)]} {year}",
    )


@bp.route('/<int:year>/<month>/<handle>/')
def single_article(year, month, handle):
    start, end = arrow.get(year, int(month), 1).span('month')
    article = Article.query if current_user.is_authenticated else Article.published()
    article = (
        article.filter(Article.date_published.between(start, end))
        .filter_by(handle=handle)
        .first_or_404()
    )
    return render_template('blog/views/single_article.html', article=article)

lemonade_soapbox/templates/blog/views/article_list.html
{% extends 'blog/layouts/main.html' %}
{% from 'macros.html' import time, read_more, render_pagination %}
{% from 'frontend/macros.html' import pagetitle %}

{% block body_main %}
{{ super() }}

{% if request.endpoint == 'search' %}
    {% if request.args.get('q') %}
        {% set description = 'You searched for <i>' ~ request.args.get('q') ~ '</i>' %}
    {% else %}
        {% set description = 'You haven\'t searched yet.' %}
    {% endif %}

    {{ pagetitle(title=("Search My Blog" if not articles else articles.total ~ " articles found"), cover=url_for('.static', filename='images/layout/header_bg/glenn-carstens-peters-RLw-UC03Gwc-unsplash.jpg'), description=description)}}
{% else %}
    {{ pagetitle(title=page_title, cover=cover, description=('No articles found' if not articles else (description or articles.total ~ " articles found")))}}

    {% block open_graph %}
        <meta property="og:url" content="{{ request.base_url }}">
        <meta property="og:type" content="website">
        <meta property="og:title" content="{{ self.page_title() }}">
        {% if articles.items %}
        <meta property="og:description" content="{{ articles.total }} articles under this tag. Latest book: {{ articles.items[0].short_title }}">
        {% else %}
        <meta property="og:description" content="No articles found.">
        {% endif %}
        <meta property="og:image" content="{{ cover }}">
        <meta name="twitter:card" content="summary_large_image">
    {% endblock %}
{% endif %}

{% if request.endpoint == 'show_tag' and articles %}
{% block feeds %}
    {{ super() }}

    <link rel="alternate"  href="{{ url_for('blog.show_tag', format='rss', handle=handle) }}" title="Articles for this tag - RSS"/>
    <link rel="alternate" href="{{ url_for('blog.show_tag', format='atom', handle=handle) }}" title="Articles for this tag - Atom"/>
{% endblock feeds %}
{% endif %}

{% block article_list %}
{% if articles and articles|attr('pages')|default(0) > 1 %}
    <div class="flex flex-col items-center my-12 md:flex-row md:justify-between md:pb-3 md:mx-10 md:border-b xl:mx-auto xl:max-w-4xl md:border-slate-400">
        <p>Showing {{ 1 + articles.per_page * (articles.page - 1) }} to {{ [articles.total, articles.per_page * articles.page]|min }} of {{ articles.total }} results</p>
    {{ render_pagination(articles) }}
    </div>
{% endif %}

{% if prev_link or next_link %}
    <div class="flex justify-between pb-3 my-12 mx-6 border-b xl:mx-auto xl:max-w-4xl border-slate-400">
        {% if prev_link %}<a class="font-bold" href="{{ prev_link[0] }}">&larr; {{ prev_link[1] }}</a>{% endif %}
        {% if next_link %}<a class="font-bold" href="{{ next_link[0] }}">{{ next_link[1] }} &rarr;</a>{% endif %}
    </div>
{% endif %}

<main>

<div class="mx-auto mt-12 max-w-4xl text-center">
    {% if not articles %}
    <p>No results found.</p>
    {% endif %}
</div>

{% if articles %}
<ol>
    {% for article in (articles.items or articles) %}
    <li>
        <article id="{{ article.handle }}" class="flex flex-col md:grid md:grid-cols-[fit-content(40%)_1fr] mt-12 mx-3 md:mt-16 md:grid-rows-[repeat(2,_min-content)] md:gap-x-8 md:gap-y-2 md:mx-10 xl:mx-auto xl:max-w-4xl lg:gap-x-2 lg:shadow-md lg:shadow-slate-600/25 lg:rounded-b-lg lg:overflow-hidden lg:border-t-8 lg:border-fuchsia-900 group hover:border-sky-900 hover:shadow-slate-600/50 focus-within:border-sky-900 focus-within:shadow-slate-600/50">

            <header class="contents">
                <a href="{{ article.get_permalink() }}" class="md:row-span-full lg:p-3">
                    {% if article.cover %}
                    <img src="/media/article/covers/{{ article.cover }}" alt="Cover image for {{ article.title }}" class="mb-3 shadow-md md:mb-0 lg:opacity-90 shadow-slate-600/50 group-hover:lg:opacity-100 group-hover:shadow-slate-600/100 group-focus-within:lg:opacity-100 group-focus-within:shadow-slate-600/100">
                    {% endif %}
                </a>

                <div>
                    <h3 class="mb-2 text-xl lg:pt-3 lg:font-bold"><a class="hover:underline focus:underline group-hover:text-sky-900 group-focus-within:text-sky-900" href="{{ article.get_permalink() }}">{{ article.title }}</a></h3>

                    <p class="pb-2 mb-2 font-light border-b md:mb-0 border-slate-400">
                    {% if article.status == "published" %}
                        Published {{ time(article.date_published, 'MMMM D, YYYY') }}
                    {% endif %}
                    {% if article.status != "published" or article.show_updated %}
                        <small class="block">(Updated {{ time(article.date_updated, 'MMMM D, YYYY') }})</small> 
                    {% endif %}
                    </p>
                </div>
            </header>

            <div class="sm:block sm:font-serif">
                <div class="sm:max-w-none md:pb-3 lg:pr-3 prose prose-slate prose-sm prose-img:max-h-[50vh] prose-img:mx-auto sm:prose-h2:text-base lg:prose-base lg:prose-h2:text-base group-hover:prose-p:text-slate-900">
                {{ article.summary or article.body_html|truncate_html(read_more_length|default(75)) }}
                </div>
            </div>             
        </article>
    </li>
{% endfor %}
</ol>

{% if articles and articles|attr('pages')|default(0) > 1 %}
    <div class="flex flex-col items-center my-12 md:flex-row md:justify-between md:pt-3 md:mx-10 md:border-t lg:mx-auto lg:max-w-4xl md:border-slate-400">
        <p>Showing {{ 1 + articles.per_page * (articles.page - 1) }} to {{ [articles.total, articles.per_page * articles.page]|min }} of {{ articles.total }} results</p>
    {{ render_pagination(articles) }}
    </div>
{% endif %}
</main>
{% endif %}
{% endblock article_list %}
{% endblock body_main %}

lemonade_soapbox/templates/blog/views/index.html
{% extends 'blog/views/article_list.html' %}

{% block article_list %}
	<div class="lg:grid lg:grid-cols-8 lg:grid-flow-col-dense lg:mx-auto lg:max-w-5xl">

		<nav class="mt-12 lg:col-span-2 lg:col-start-1" aria-labelledby="explore">
			<h2 class="text-lg lg:text-xl sidebar-heading" id="explore">Explore My Blog</h2>
			<a class="block mx-6 mt-3 lg:text-lg" href="{{ url_for('.all_tags') }}">View Tags</a>

			<h3 class="mx-6 mt-6 font-bold text-sky-900">View by Year</h3>
			<ul class="flex flex-wrap mx-6 lg:grid lg:grid-cols-4">
				{% for y in range(arrow.now().year, 2003, -1) %}
					<li class="mt-3 mr-4 lg:text-lg"><a href="{{ url_for('.year_archive', year=y) }}">{{ y }}</a></li>
				{% endfor %}
			</ul>
		</nav>

		<div class="lg:col-span-5 lg:col-start-4">
			{{ super() }}
		</div>
	</div>
{% endblock %}

lemonade_soapbox/templates/blog/views/single_article.html
{% extends 'blog/layouts/main.html' %}
{% from 'macros.html' import read_more, time %}
{% from 'frontend/macros.html' import pagetitle %}

{% block meta_tags %}
<meta property="og:url" content="{{ article.get_permalink(False) }}" />
<meta property="og:type" content="article" />
<meta property="og:title" content="{{ article.title }} | Kara Babcock’s Blog" />
<meta property="og:description" content="{{ article.summary or read_more(article.body_html, length=50, link=False)|striptags }}" />
<meta name="twitter:card" content="summary_large_image"/>
{% if article.cover %}
<meta property="og:image" content="{{ request.url_root }}media/article/covers/{{ article.cover }}"/>
{% else %}
        <meta property="og:image" content="{{ url_for('.static', filename='images/headshots/kara-babcock-2024-04-06 12.24.39.jpg', _external=True) }}">
        <meta property="og:image:width" content="1458">
        <meta property="og:image:height" content="1860">
{% endif %}
{% endblock %}

{% block page_title %}
{{ article.title }} {{ super() }}
{% endblock %}


{% block body_main %}
    {{ super() }}

<article id="{{ article.handle }}" data-id="{{ article.id }}">
    <header>
        {{ pagetitle(title=article.title, description=article.summary, cover=(('/media/article/covers/' ~ article.cover) if article.cover else '')) }}
    </header>

<div class="mt-12 lg:mt-8 lg:grid lg:grid-cols-[minmax(auto,_calc(50vw-28rem))_repeat(2,_35ch)_auto_auto_minmax(auto,_calc(50vw-28rem))] lg:gap-2 xl:gap-4"><!-- Grid layout begin -->
    <footer class="px-6 text-sm sm:text-base lg:col-span-3 lg:col-start-2 lg:row-start-1 text-slate-500">
        <p>
        {% if article.status == 'published' %}
           Published {{ time(article.date_published, format='dddd, MMMM D, YYYY h:mm A ZZ') }}.
        {% endif %}
        </p>
        {% if article.show_updated and article.date_updated > article.date_published %}
        <p>Last updated {{ time(article.date_updated, format='MMMM D, YYYY') }}.</p>
        {% endif %}

        {% if article.tags %}
        <div class="mt-6">
            Tags: 
            <ul class="inline">
                {% for t in article._tags|sort(attribute='handle') %}
                <li class="inline after:content-[',_'] last:after:content-['.']"><a class="underline text-slate-500" href="{{ url_for('.show_tag', handle=t.handle) }}" rel="tag">{{ t.label }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% if current_user.is_authenticated %}
            <p class="mt-6"><a class="underline" href="{{ article.get_editlink() }}">Edit post</a></p>
        {% endif %}
    </footer>

    <aside class="mt-12 lg:col-start-5 lg:col-end-7 lg:row-span-2 lg:row-start-1 lg:mt-0 xl:col-end-6">
        <h3 class="last:hidden sidebar-heading">Heads Up</h3>
        {% if article.status == "published" and (arrow.utcnow() - article.date_published) > timedelta(days=728) %}
        <p class="px-3 mt-4 text-sm text-slate-500">
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-block w-4 h-4 align-top mt-[0.15rem]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <strong>This post was published {{ article.date_published.humanize() }}.</strong> Some of its information or my opinions might be out of date.
        </p>
        {% endif %}

        {% if article.status == "published" and article.date_published < arrow.get(config.TRANS_DATE) %}
        <p class="px-3 mt-4 text-sm text-slate-500">I wrote this before I came out as transgender. As such, I might refer to myself as a man or use my deadname. Please read my <a href="/about#name">name policy</a>.</p>
        {% endif %}
    </aside>

    <div class="px-6 mt-16 lg:col-span-3 lg:col-start-2 lg:row-span-3 lg:row-start-2 lg:mt-8">
        <div class="dropcap endmark prose prose-slate prose-p:indent-4 prose-img:mx-auto prose-img:shadow-md prose-img:shadow-slate-900/50 prose-figcaption:text-center prose-video:mx-auto prose-video:shadow-md prose-video:shadow-slate-900/50 md:prose-md lg:prose-lg lg:prose-video:max-h-[75vh] lg:prose-img:max-h-[75vh] xl:prose-figure:-mx-16">
        {{ article.body_html }}
        </div>
    </div>

    <aside class="py-6 mt-24 md:py-12 lg:col-span-full lg:row-start-5 bg-sky-900">

    <div class="flex flex-col md:flex-row md:flex-wrap md:mx-auto md:max-w-4xl md:text-sm">

    {% set padding = "md:pt-60" %}
    {% if (article.previous_post and article.next_post) and not(article.previous_post.cover or article.next_post.cover) %}
        {% set padding = "md:pt-0" %}
    {%  endif %}

    {% if article.previous_post %}
        <a class="pb-6 mx-3 md:flex-1 md:pb-0 group" href="{{ article.previous_post.get_permalink() }}">
            <article class="flex flex-col items-start">
                {% if article.previous_post.cover %}
                    <img class="-mx-3 mb-8 w-screen max-w-none shadow-lg md:mx-3 md:w-auto md:h-52 md:opacity-90 group-hover:opacity-100 group-focus:opacity-100 shadow-slate-400/50" src="/media/article/covers/{{ article.previous_post.cover }}" alt="Cover image for {{ article.previous_post.title }}">
                {%  endif %}

                <div class="{{ padding if not article.previous_post.cover }} w-full px-3 font-bold text-sky-100">&larr; {{ time(article.previous_post.date_published, format="MMM DD") }}</div>

                <h2 class="px-3 font-bold group-hover:text-fuchsia-300 group-focus:text-fuchsia-300 text-slate-100">{{ article.previous_post.title }}</h2>
                <p class="px-3 font-light text-slate-50 group-hover:text-slate-200 group-focus:text-slate-200">{{ article.previous_post.summary or read_more(article.previous_post.body_html, length=50, link=False)|striptags }}</p>
            </article>
        </a>
    {% endif %}

    {% if article.next_post %}
        <a class="pt-6 mx-3 md:flex-1 md:pt-0 group" href="{{ article.next_post.get_permalink() }}">
            <article class="flex flex-col items-end">
                {% if article.next_post.cover %}
                    <img class="-mx-3 mb-8 w-screen max-w-none shadow-lg md:mx-3 md:w-auto md:h-52 md:opacity-90 group-hover:opacity-100 group-focus:opacity-100 shadow-slate-400/50" src="/media/article/covers/{{ article.next_post.cover }}" alt="Cover image for {{ article.next_post.title }}">
                {%  endif %}

                <div class="{{ padding if not article.next_post.cover }} w-full px-3 font-bold text-sky-100 text-right">{{ time(article.next_post.date_published, format="MMM DD") }} &rarr;</div>

                <h2 class="px-3 font-bold text-right group-hover:text-fuchsia-300 group-focus:text-fuchsia-300 text-slate-100">{{ article.next_post.title }}</h2>
                <p class="px-3 font-light text-right text-slate-50 group-hover:text-slate-200 group-focus:text-slate-200">{{ article.next_post.summary or read_more(article.next_post.body_html, length=50, link=False)|striptags }}</p>
            </article>
        </a>
    {% endif %}
    </div>
    </aside>
</div> <!-- Grid layout end -->
</article>
{% endblock %}

lemonade_soapbox/templates/blog/views/tags.html
{% extends 'frontend/layouts/main.html' %}
{% from 'frontend/macros.html' import pagetitle %}

{% block body_main %}
{{ super() }}

{{ pagetitle(title=page_title, cover=url_for('.static', filename='images/layout/header_bg/jan-antonin-kolar-lRoX0shwjUQ-unsplash.jpg'), description="An easy way to browse my blog posts by categories.")}}

<main>
    <div class="p-3 mt-12 text-lg text-center">
        <p>Sort tags  
        {% if sort_by != 'alphabetical' %}
            <a href="?sort=alphabetical" class="border-b-2 border-fuchsia-900 hover:border-sky-900 focus:border-sky-900">alphabetically</a> 
        {% else %}
            <strong>alphabetically</strong>
        {% endif %}
        | 
        {% if sort_by != 'frequency' %}
        <a href="?sort=frequency" class="border-b-2 border-fuchsia-900 hover:border-sky-900 focus:border-sky-900">by number of books</a>
        {% else %}
            <strong>by number of articles</strong>
        {% endif %}
        </p>

        {% if tags and sort_by != 'frequency' %}
        <div class="mt-6">
            Jump to: 
            <ul class="flex flex-wrap justify-center">
            {% for letter, tags in tags|groupby("0.handle.0") %}
                <li><a class="block p-1 mt-2 mr-4 border-b-2 border-fuchsia-900 hover:border-sky-900 focus:border-sky-900" href="#letter-{{ letter }}">{{ letter.upper() }}</a></li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>

    {% if tags %}
        {% if sort_by == 'frequency' %}
            <ul class="flex flex-wrap justify-center mx-auto mt-12 lg:max-w-4xl">
            {% for tag in tags|sort(attribute="1", reverse=True)|weight %}
                <li>
                    <a href="{{ url_for('.show_tag', handle=tag[0].handle) }}" class="block mt-3 mr-2 p-3 lg:mt-6 lg:mr-4 tracking-wide rounded-md shadow-md transition-all duration-300 lg:leading-5 hover:bg-fuchsia-800 active:relative active:top-px active:left-px active:bg-fuchsia-700 bg-fuchsia-800/75 text-slate-50 shadow-slate-900/50 hover:text-slate-50 focus:bg-fuchsia-800 focus:text-slate-50 active:text-slate-50 text-[length:calc(var(--weight)*1.5rem)]" style="--weight: {{ tag[2] }}">{{ tag[0].label }}</span>
                    <span class="text-slate-100">({{ tag[1] }})</span></a>
                </li>
            {% endfor %}
            </ul>
        {% else %}

        <div class="pt-12 mt-12 sm:items-start sm:border-t lg:container lg:mx-auto border-slate-400 sm:columns-2 md:columns-3">
            {% for letter, tag_list in tags|groupby("0.handle.0") %}
            <div class="mb-12 break-inside-avoid-column" id="letter-{{ letter }}">
                <h2 class="text-center"><span class="inline-block pb-3 w-12 bg-[url('/assets/images/icons/open-book.svg')] bg-bottom bg-no-repeat bg-[length:2em_auto] text-3xl font-bold text-center">{{ letter.upper() }}</span></h2>
                <ul class="text-center">
                {% for tag in tag_list %}
                    <li><a class="underline" href="{{ url_for('.show_tag', handle=tag[0].handle) }}" title="{{ tag[1] }} articles">{{ tag[0].label }}</a></li>
                {% endfor %}
                </ul>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    {% endif %}
</main>
{% endblock body_main %}

lemonade_soapbox/templates/blog/views/year_archive.html
{% extends 'blog/layouts/main.html' %}
{% from 'macros.html' import time %}
{% from 'frontend/macros.html' import pagetitle %}

{% block body_main %}

{{ super() }}

{{ pagetitle(title=page_title, description=year_summaries[year|string]) }}

{% if prev_link or next_link %}
	<div class="flex justify-between pb-3 my-12 mx-6 border-b xl:mx-auto xl:max-w-4xl border-slate-400">
		{% if prev_link %}<a class="font-bold" href="{{ url_for('blog.year_archive', year=(year - 1)) }}">&larr; {{ year - 1 }}</a>{% endif %}
		{% if next_link %}<a class="font-bold" href="{{ url_for('blog.year_archive', year=(year + 1)) }}">{{ year + 1 }} &rarr;</a>{% endif %}
	</div>
{% endif %}

<ol reversed class="mt-12 lg:mx-auto lg:max-w-4xl">
	{% for month in articles|groupby('date_published.month')|sort(True, month) %}
	<li>
			<h2 class="mx-6 mt-12"><a class="text-2xl font-bold underline text-sky-900 hover:text-sky-900 focus:text-sky-900" title="View articles from this month in more detail" href="{{ url_for('blog.month_archive', year=year, month=('%02d' % month.grouper)) }}">{{ month_name[month.grouper] }}</a></h2>

			<ol reversed>
				{% for article in month.list|sort(True, attribute='date_published.day') %}
				<li class="mx-6 mt-3">
					{{ time(article.date_published, format="MMM DD", class="lg:text-sm") }}

					<a class="ml-2" href="{{ article.get_permalink() }}">{{ article.title }}</a>
				</li>
				{% endfor %}
			</ol>
	</li>
	{% endfor %}
</ol>
{% endblock %}